#!/usr/bin/env bash
set -eo pipefail

echo "rekeying for recipients: $(cat $AGE_RECIPIENTS_FILE)"
for file in "$@"; do
  echo "rekeying $file"
  age -R "$AGE_RECIPIENTS_FILE" -o "$file" <<< "$(age-decrypt "$file")"
done
