#!/usr/bin/env bash
set -euo pipefail

age -i $XDG_RUNTIME_DIR/age -d "$1" 2>/dev/null || \
  age -i ~/age-tpm.txt -d "$1" 2>/dev/null || \
  age -i <(age-plugin-yubikey --identity --slot 1 2>/dev/null) -d "$1"
