#!/usr/bin/env bash
set -euo pipefail

# TODO: remove this hack once https://github.com/str4d/age-plugin-yubikey/issues/136
# is resolved. The PIN is now requested too frequently. Keygrip doesn't contain
# secret information and it's OK to linger in /tmp.
ykid=/tmp/yubi-id
test -f $ykid || age-plugin-yubikey --identity --slot 1 > $ykid 2>/dev/null
age -i $ykid -d "$@"
