#!/usr/bin/env bash
set -euo pipefail

DEFAULT_MODEL="opencode/glm-5-free"

# In case the model leaves some files in the temp directory instead of answering
destroy() {
  rm -rf "$tmpdir"
}

tmpdir="$(mktemp -d)"
trap destroy EXIT
cd $tmpdir

if [[ $1 == '--model' ]] || [[ $1 == '-m' ]]; then
  echo "model provided: $2"
  model="$2"
  shift
  shift
fi

set -x
opencode run -m ${model:-$DEFAULT_MODEL} ${*}
