#!/usr/bin/env bash

# Fuzzy finds branches except your current branch, returns the selected branch
fuzzy_branch() {
  git branch | grep -Ev '\*' | fzf | tr -d ' '
}

branch=${1:-$(fuzzy_branch)}
set -e
if [[ -n $branch ]]; then
  git branch -D "$branch"
  read -p "Delete '$branch' from remote? [yN]: " -n1 ans
  echo

  if [[ $ans = 'y' ]]; then
    set +e
    ( git push origin ":$branch" ) &
  fi
fi

