#!/usr/bin/env bash
set -euo pipefail

cd $PASSWORD_STORE_DIR/Credit-Card
file=$(fd --type f | $FUZZY)

cc_data=$(age -d -i <(age-plugin-yubikey -i) "$file")
grep '^number' <<< "$cc_data" | sed 's/number: //' | pbcopy

echo "$cc_data"
