#!/usr/bin/env -S sh -c 'nix shell nixpkgs#{bash,jq,bc,curl,ansifilter} -c bash "$0" "$@"'

declare -a tickers=("^GSPC" "BTC-USD" "TLT" "GLD")

user_agents=(
    # Chrome
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36"
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36"
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36"
    # Firefox
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0"
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14.7; rv:135.0) Gecko/20100101 Firefox/135.0"
    "Mozilla/5.0 (X11; Linux i686; rv:135.0) Gecko/20100101 Firefox/135.0"
    # Safari
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_7_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Safari/605.1.15"
    # Edge
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/131.0.2903.86"
)

ua=${user_agents[ $RANDOM % ${#user_agents[@]} ]}

for ticker in "${tickers[@]}"; do
    result=$(curl -s -H "User-Agent: $ua" "https://query1.finance.yahoo.com/v8/finance/chart/$ticker")
    price=$(echo "$result" | jq -r '.chart.result[0].meta.regularMarketPrice')
    prev_close=$(echo "$result" | jq -r '.chart.result[0].meta.previousClose')
    pct_change=$(echo "$price $prev_close" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
    
    if (( $(echo "$pct_change >= 0" | bc -l) )); then
        color="\033[32m"  # Green for positive/zero
    else
        color="\033[31m"  # Red for negative
    fi
    
    printf "%s: ${color}$%.1f (%.2f%%)\033[0m " "$ticker" "$price" "$pct_change"
done
echo
