#!/usr/bin/env bash

if [[ $1 == .#* ]]; then
  nix run $*
elif [[ -n $1 ]]; then
  prefix=nixpkgs#
  if [[ $1 == github:* ]]; then prefix=; fi
  if [[ $1 == '--' ]]; then prefix='. '; fi

  set -x
  nix run $prefix$* 
else
  set -x
  nix run
fi
