#!/usr/bin/env bash
set -euo pipefail

account=$(ls $OTPDIR | fzf)
file="$OTPDIR/$account"

if [[ ! -f "$file" ]]; then
  echo "Unknown file: $file"
  exit 1
fi


value=$(age -d -i <(age-plugin-yubikey -i) "$file")
code=$(oathtool --base32 --totp "$value")
echo "Code: $code"

# copy to clipboard
echo $code | pbcopy
echo "OTP $account copied to the clipboard."
