#!/usr/bin/env bash

(
    set -euo pipefail
    cd $PASSWORD_STORE_DIR/Password
    file=$(rg --files | $FUZZY)
    contents=$(gpg --quiet --decrypt $file | head -n 1)
    echo -n $contents | pbcopy
)
