#!/usr/bin/env bash
set -euo pipefail

cd $PASSWORD_STORE_DIR/Password
file=$(fd --type f | fzf)
IFS=$'\n'
contents=$(age-decrypt "$file")
password=$(head -n 1 <<< $contents)
username=$(grep -e '^username:' <<< $contents)

pbcopy <<< "${username#username: }"
echo "Username copied to the clipboard. Press Enter when ready."

read -r enter
pbcopy <<< $password
echo "Password copied to the clipboard. Make sure you trash it."
