[theme]
name = "native"
[icons]
name = "awesome"

[theme.overrides]
critical_fg = "#FF5555"
warning_fg = "#F96A02"

[[block]]
block = "sound"
format = ""

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui-connect"
ap_format = "{ssid}"
device_format = "{icon}{ap}"

[[block]]
block = "battery"
interval = 10
driver = "upower"
format = "{percentage}"

[[block]]
block = "time"
interval = 60
format = "%a %b %-d %R"
on_click = "gnome-clocks"
icons_format = ""
