[theme]
theme = "native"
[icons]
icons = "awesome6"

[theme.overrides]
critical_fg = "#FF5555"
warning_fg = "#F96A02"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str() |"
short = " $title.str(max_w:10) |"

[[block]]
block = "custom"
command = "fin | ansifilter --pango | tr -d '\n'"
shell = "bash"
interval = 600

[[block]]
block = "cpu"
format_alt = "$barchart"

[[block]]
block = "custom"
command = '''cat /sys/firmware/acpi/platform_profile'''
shell = "bash"

[[block]]
block = "memory"
format = "$icon $mem_used"
format_alt = " $icon $mem_total_used_percents"

[[block]]
block = "sound"
format = "$icon"
[[block.click]]
button = "left"
cmd = "pwvucontrol"

[[block]]
block = "bluetooth"
mac = "84:5C:F3:93:79:42"
[[block.click]]
button = "left"
cmd = "blueberry"

[[block]]
block = "net"
format = "$icon"
[[block.click]]
button = "left"
cmd = "kitty --title floating_term nmtui connect"

[[block]]
block = "battery"
interval = 10
empty_format = " $icon $percentage "
missing_format =  ""

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%a %b %-d %R')"
[[block.click]]
button = "left"
cmd = "gnome-clocks"
