[theme]
name = "native"
[icons]
name = "awesome5"

[theme.overrides]
critical_fg = "#FF5555"
warning_fg = "#F96A02"

[[block]]
block = "cpu"
format = "{barchart}"
icons_format = ""

[[block]]
block = "custom"
command = ''' bash -c "notmuch count --output=threads 'folder:/.*/Inbox/' 2>/dev/null || echo 0" | jq '{icon:"mail", text: . | tostring}' '''
on_click = "astroid"
json = true
interval = 10

[[block]]
block = "sound"
format = ""

[[block]]
block = "bluetooth"
mac = "84:5C:F3:93:79:42"
on_click = "blueberry"
format_unavailable = ""

[[block]]
block = "networkmanager"
on_click = "foot --title floating_term nmtui connect"
ap_format = "{ssid}"
device_format = "{icon}{ap}"
interface_name_exclude = ["virbr[0-9]", "br\\-[0-9a-f]{12}", "docker\\d+"]

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
allow_missing = true
hide_missing = true

[[block]]
block = "time"
interval = 60
format = "%a %b %-d %R"
on_click = "gnome-clocks"
icons_format = ""
