[theme]
name = "native"
[icons]
name = "awesome"

[theme.overrides]
critical_fg = "#FF5555"
warning_fg = "#F96A02"

[[block]]
block = "custom"
on_click = "swaymsg workspace 4"
command = '''n=$(notmuch count --output=threads 'path:/.*/Inbox/' 2>/dev/null); test $n -ne 0 && echo -e "\uf0e0 $n"'''
hide_when_empty = true
shell = "bash"

[[block]]
block = "cpu"
format = "{barchart}"
icons_format = ""

[[block]]
block = "memory"
format_mem = "{mem_used;M}"

[[block]]
block = "sound"
format = ""

[[block]]
block = "bluetooth"
mac = "84:5C:F3:93:79:42"
on_click = "blueberry"
format_unavailable = ""

[[block]]
block = "networkmanager"
on_click = "kitty --title floating_term nmtui connect"
ap_format = "{ssid}"
device_format = "{icon}{ap}"
interface_name_exclude = ["virbr[0-9]", "br\\-[0-9a-f]{12}", "docker\\d+"]

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
hide_missing = true

[[block]]
block = "time"
interval = 60
format = "%a %b %-d %R"
on_click = "gnome-clocks"
icons_format = ""
