[theme]
theme = "native"
[icons]
icons = "awesome6"

[theme.overrides]
critical_fg = "#FF5555"
warning_fg = "#F96A02"

[[block]]
block = "external_ip"
format = "$ip"

[[block]]
block = "custom"
command = '''n=$(notmuch count --output=threads 'path:/.*/Inbox/' 2>/dev/null); test $n -ne 0 && echo -e "\uf0e0 $n"'''
hide_when_empty = true
shell = "bash"
[[block.click]]
button = "left"
cmd = "swaymsg scratchpad show"

[[block]]
block = "cpu"
format = "$barchart $frequency"

[[block]]
block = "custom"
command = '''cat /sys/firmware/acpi/platform_profile'''
shell = "bash"

[[block]]
block = "memory"
format = " $icon $mem_used"
format_alt = " $icon $mem_total_used_percents"

[[block]]
block = "sound"
format = "$icon"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "84:5C:F3:93:79:42"
[[block.click]]
button = "left"
cmd = "blueberry"

[[block]]
block = "net"
format = "$icon {$ssid}"
[[block.click]]
button = "left"
cmd = "kitty --title floating_term nmtui connect"

[[block]]
block = "battery"
interval = 10

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%a %b %-d %R')"
[[block.click]]
button = "left"
cmd = "gnome-clocks"
