[theme]
theme = "native"
[icons]
icons = "awesome6"

[theme.overrides]
critical_fg = "#FF5555"
warning_fg = "#F96A02"

[[block]]
block = "custom"
command = 'grep "\- \[ \]" ~/base/todo.md | head -n 1 | cut -f2 -d] | xargs'
shell = "bash"
interval = 60

# [[block]]
# block = "custom"
# command = "fin | ansifilter --pango | tr -d '\n'"
# shell = "bash"
# interval = 60

[[block]]
block = "custom"
command = "tmux-mem-cpu-load -t 1 -a 0 -v"

[[block]]
block = "custom"
command = '''cat /sys/firmware/acpi/platform_profile'''
shell = "bash"

[[block]]
block = "sound"
format = "$icon"
[[block.click]]
button = "left"
cmd = "pwvucontrol"

[[block]]
block = "bluetooth"
mac = "84:5C:F3:93:79:42"
[[block.click]]
button = "left"
cmd = "blueberry"

[[block]]
block = "net"
format = "$icon"
[[block.click]]
button = "left"
cmd = "kitty --title floating_term nmtui connect"

[[block]]
block = "battery"
interval = 10
empty_format = " $icon $percentage "
missing_format =  ""

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%a %b %-d %R')"
[[block.click]]
button = "left"
cmd = "gnome-clocks"
